name: fli
description: A native CLI tool for generating clean and standardized Flutter project structures. Supports all platforms with optimized functionality for desktop use.
version: 1.1.2
homepage: https://github.com/faizahmaddae/fli
repository: https://github.com/faizahmaddae/fli
issue_tracker: https://github.com/faizahmaddae/fli/issues
documentation: https://github.com/faizahmaddae/fli#readme
funding:
  - https://buymeacoffee.com/faizahmaddae

# Help users and pub.dev understand this is a CLI tool
topics:
  - cli
  - flutter
  - generator
  - scaffold
  - project-structure

environment:
  sdk: '>=3.0.0 <4.0.0'

# This is a CLI tool that supports all platforms
# Note: While primarily designed for desktop use, it can run on all platforms
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  args: ^2.4.2
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0

executables:
  fli:
