name: fli
description: A native CLI tool for generating clean and standardized Flutter project structures. Designed for command-line use on desktop platforms.
version: 1.0.0
homepage: https://github.com/faizahmaddae/fli
repository: https://github.com/faizahmaddae/fli
issue_tracker: https://github.com/faizahmaddae/fli/issues
documentation: https://github.com/faizahmaddae/fli#readme

# Help users and pub.dev understand this is a CLI tool
topics:
  - cli
  - flutter
  - generator
  - scaffold
  - project-structure

environment:
  sdk: '>=3.0.0 <4.0.0'

# This is a CLI tool that requires native platform capabilities
# Web/WASM compatibility is not applicable for command-line tools
platforms:
  linux:
  macos:
  windows:

dependencies:
  args: ^2.4.2
  path: ^1.9.0
  yaml: ^3.1.2
  mason: ^0.1.1
  mason_cli: ^0.1.2

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0

executables:
  fli:
